# TCL File Generated by Component Editor 25.1
# Mon Jun 08 12:43:21 CEST 2026
# DO NOT MODIFY


# 
# ltc2308_ctl "ltc2308_ctl" v1.0
#  2026.06.08.12:43:21
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ltc2308_ctl
# 
set_module_property DESCRIPTION ""
set_module_property NAME ltc2308_ctl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ltc2308_ctl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ltc2308_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file timer.sv SYSTEM_VERILOG PATH ../rtl/timer.sv
add_fileset_file ltc2308_ctl.sv SYSTEM_VERILOG PATH ../rtl/ltc2308_ctl.sv TOP_LEVEL_FILE
add_fileset_file ctl.sv SYSTEM_VERILOG PATH ../rtl/ctl.sv
add_fileset_file sck_generator.sv SYSTEM_VERILOG PATH ../rtl/spi/sck_generator.sv
add_fileset_file spi.sv SYSTEM_VERILOG PATH ../rtl/spi/spi.sv
add_fileset_file spi_master.sv SYSTEM_VERILOG PATH ../rtl/spi/spi_master.sv
add_fileset_file csr.sv SYSTEM_VERILOG PATH ../rtl/csr/csr.sv
add_fileset_file csr_pkg.sv SYSTEM_VERILOG PATH ../rtl/csr/csr_pkg.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point adc_spi
# 
add_interface adc_spi conduit end
set_interface_property adc_spi associatedClock clock
set_interface_property adc_spi associatedReset ""
set_interface_property adc_spi ENABLED true
set_interface_property adc_spi EXPORT_OF ""
set_interface_property adc_spi PORT_NAME_MAP ""
set_interface_property adc_spi CMSIS_SVD_VARIABLES ""
set_interface_property adc_spi SVD_ADDRESS_GROUP ""

add_interface_port adc_spi spi_sck adc_sclk Output 1
add_interface_port adc_spi spi_mosi adc_sdi Output 1
add_interface_port adc_spi spi_convst adc_convst Output 1
add_interface_port adc_spi spi_miso adc_sdo Input 1


# 
# connection point avalon_mm
# 
add_interface avalon_mm avalon end
set_interface_property avalon_mm addressUnits WORDS
set_interface_property avalon_mm associatedClock clock
set_interface_property avalon_mm associatedReset reset
set_interface_property avalon_mm bitsPerSymbol 8
set_interface_property avalon_mm burstOnBurstBoundariesOnly false
set_interface_property avalon_mm burstcountUnits WORDS
set_interface_property avalon_mm explicitAddressSpan 0
set_interface_property avalon_mm holdTime 0
set_interface_property avalon_mm linewrapBursts false
set_interface_property avalon_mm maximumPendingReadTransactions 0
set_interface_property avalon_mm maximumPendingWriteTransactions 0
set_interface_property avalon_mm readLatency 0
set_interface_property avalon_mm readWaitTime 1
set_interface_property avalon_mm setupTime 0
set_interface_property avalon_mm timingUnits Cycles
set_interface_property avalon_mm writeWaitTime 0
set_interface_property avalon_mm ENABLED true
set_interface_property avalon_mm EXPORT_OF ""
set_interface_property avalon_mm PORT_NAME_MAP ""
set_interface_property avalon_mm CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm avalon_byteenable byteenable Input 4
add_interface_port avalon_mm avalon_readdata readdata Output 32
add_interface_port avalon_mm avalon_waitrequest waitrequest Output 1
add_interface_port avalon_mm avalon_writedata writedata Input 32
add_interface_port avalon_mm avalon_address address Input 2
add_interface_port avalon_mm avalon_read read Input 1
add_interface_port avalon_mm avalon_write write Input 1
set_interface_assignment avalon_mm embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm embeddedsw.configuration.isPrintableDevice 0

