// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module csr (
        input wire clk,
        input wire arst_n,

        input wire avalon_read,
        input wire avalon_write,
        output logic avalon_waitrequest,
        input wire [1:0] avalon_address,
        input wire [31:0] avalon_writedata,
        input wire [3:0] avalon_byteenable,
        output logic avalon_readdatavalid,
        output logic avalon_writeresponsevalid,
        output logic [31:0] avalon_readdata,
        output logic [1:0] avalon_response,

        input csr_pkg::csr__in_t hwif_in,
        output csr_pkg::csr__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    always_comb begin
        cpuif_req = avalon_read | avalon_write;
        cpuif_req_is_wr = avalon_write;
        cpuif_addr = {avalon_address, 2'b0};
        cpuif_wr_data = avalon_writedata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{avalon_byteenable[i]}};
        end
        avalon_waitrequest = (cpuif_req_stall_rd & avalon_read) | (cpuif_req_stall_wr & avalon_write);
    end

    // Response
    always_comb begin
        avalon_readdatavalid = cpuif_rd_ack;
        avalon_writeresponsevalid = cpuif_wr_ack;
        avalon_readdata = cpuif_rd_data;
        if(cpuif_rd_err || cpuif_wr_err) begin
            // SLVERR
            avalon_response = 2'b10;
        end else begin
            // OK
            avalon_response = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic ctrl;
        logic cfg;
        logic data;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.ctrl = cpuif_req_masked & (cpuif_addr == 4'h0) & cpuif_req_is_wr;
        decoded_reg_strb.cfg = cpuif_req_masked & (cpuif_addr == 4'h4) & cpuif_req_is_wr;
        decoded_reg_strb.data = cpuif_req_masked & (cpuif_addr == 4'h8) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } start_conv;
        } ctrl;
        struct {
            struct {
                logic next;
                logic load_next;
            } sleep;
            struct {
                logic next;
                logic load_next;
            } unipolar;
            struct {
                logic [1:0] next;
                logic load_next;
            } channel_addr;
            struct {
                logic next;
                logic load_next;
            } odd;
            struct {
                logic next;
                logic load_next;
            } single_ended;
        } cfg;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } start_conv;
        } ctrl;
        struct {
            struct {
                logic value;
            } sleep;
            struct {
                logic value;
            } unipolar;
            struct {
                logic [1:0] value;
            } channel_addr;
            struct {
                logic value;
            } odd;
            struct {
                logic value;
            } single_ended;
        } cfg;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: csr.ctrl.start_conv
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ctrl.start_conv.value;
        load_next_c = '0;
        if(decoded_reg_strb.ctrl && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ctrl.start_conv.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.ctrl.start_conv.next = next_c;
        field_combo.ctrl.start_conv.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.ctrl.start_conv.value <= 1'h0;
        end else begin
            if(field_combo.ctrl.start_conv.load_next) begin
                field_storage.ctrl.start_conv.value <= field_combo.ctrl.start_conv.next;
            end
        end
    end
    assign hwif_out.ctrl.start_conv.value = field_storage.ctrl.start_conv.value;
    // Field: csr.cfg.sleep
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.cfg.sleep.value;
        load_next_c = '0;
        if(decoded_reg_strb.cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.cfg.sleep.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.cfg.sleep.next = next_c;
        field_combo.cfg.sleep.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.cfg.sleep.value <= 1'h0;
        end else begin
            if(field_combo.cfg.sleep.load_next) begin
                field_storage.cfg.sleep.value <= field_combo.cfg.sleep.next;
            end
        end
    end
    assign hwif_out.cfg.sleep.value = field_storage.cfg.sleep.value;
    // Field: csr.cfg.unipolar
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.cfg.unipolar.value;
        load_next_c = '0;
        if(decoded_reg_strb.cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.cfg.unipolar.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.cfg.unipolar.next = next_c;
        field_combo.cfg.unipolar.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.cfg.unipolar.value <= 1'h1;
        end else begin
            if(field_combo.cfg.unipolar.load_next) begin
                field_storage.cfg.unipolar.value <= field_combo.cfg.unipolar.next;
            end
        end
    end
    assign hwif_out.cfg.unipolar.value = field_storage.cfg.unipolar.value;
    // Field: csr.cfg.channel_addr
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.cfg.channel_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.cfg.channel_addr.value & ~decoded_wr_biten[3:2]) | (decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
            load_next_c = '1;
        end
        field_combo.cfg.channel_addr.next = next_c;
        field_combo.cfg.channel_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.cfg.channel_addr.value <= 2'h0;
        end else begin
            if(field_combo.cfg.channel_addr.load_next) begin
                field_storage.cfg.channel_addr.value <= field_combo.cfg.channel_addr.next;
            end
        end
    end
    assign hwif_out.cfg.channel_addr.value = field_storage.cfg.channel_addr.value;
    // Field: csr.cfg.odd
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.cfg.odd.value;
        load_next_c = '0;
        if(decoded_reg_strb.cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.cfg.odd.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.cfg.odd.next = next_c;
        field_combo.cfg.odd.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.cfg.odd.value <= 1'h1;
        end else begin
            if(field_combo.cfg.odd.load_next) begin
                field_storage.cfg.odd.value <= field_combo.cfg.odd.next;
            end
        end
    end
    assign hwif_out.cfg.odd.value = field_storage.cfg.odd.value;
    // Field: csr.cfg.single_ended
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.cfg.single_ended.value;
        load_next_c = '0;
        if(decoded_reg_strb.cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.cfg.single_ended.value & ~decoded_wr_biten[5:5]) | (decoded_wr_data[5:5] & decoded_wr_biten[5:5]);
            load_next_c = '1;
        end
        field_combo.cfg.single_ended.next = next_c;
        field_combo.cfg.single_ended.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.cfg.single_ended.value <= 1'h1;
        end else begin
            if(field_combo.cfg.single_ended.load_next) begin
                field_storage.cfg.single_ended.value <= field_combo.cfg.single_ended.next;
            end
        end
    end
    assign hwif_out.cfg.single_ended.value = field_storage.cfg.single_ended.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[1];
    assign readback_array[0][11:0] = (decoded_reg_strb.data && !decoded_req_is_wr) ? hwif_in.data.result.next : '0;
    assign readback_array[0][31:12] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<1; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
