// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 4;
    localparam CSR_SIZE = 'h10;

    typedef struct {
        logic hwclr;
        logic hwset;
    } csr__status__data_valid__in_t;

    typedef struct {
        csr__status__data_valid__in_t data_valid;
    } csr__status__in_t;

    typedef struct {
        logic [11:0] next;
    } csr__data__result__in_t;

    typedef struct {
        csr__data__result__in_t result;
    } csr__data__in_t;

    typedef struct {
        csr__status__in_t status;
        csr__data__in_t data;
    } csr__in_t;

    typedef struct {
        logic value;
    } csr__ctrl__start_conv__out_t;

    typedef struct {
        csr__ctrl__start_conv__out_t start_conv;
    } csr__ctrl__out_t;

    typedef struct {
        logic value;
    } csr__status__data_valid__out_t;

    typedef struct {
        csr__status__data_valid__out_t data_valid;
    } csr__status__out_t;

    typedef struct {
        logic value;
    } csr__cfg__sleep__out_t;

    typedef struct {
        logic value;
    } csr__cfg__unipolar__out_t;

    typedef struct {
        logic [1:0] value;
    } csr__cfg__channel_addr__out_t;

    typedef struct {
        logic value;
    } csr__cfg__odd__out_t;

    typedef struct {
        logic value;
    } csr__cfg__single_ended__out_t;

    typedef struct {
        csr__cfg__sleep__out_t sleep;
        csr__cfg__unipolar__out_t unipolar;
        csr__cfg__channel_addr__out_t channel_addr;
        csr__cfg__odd__out_t odd;
        csr__cfg__single_ended__out_t single_ended;
    } csr__cfg__out_t;

    typedef struct {
        logic swacc;
    } csr__data__result__out_t;

    typedef struct {
        csr__data__result__out_t result;
    } csr__data__out_t;

    typedef struct {
        csr__ctrl__out_t ctrl;
        csr__status__out_t status;
        csr__cfg__out_t cfg;
        csr__data__out_t data;
    } csr__out_t;
endpackage
