BBPATH .= ":${LAYERDIR}"
BBFILES:append = " ${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend "
BBFILE_COLLECTIONS:append = " meta-asicsagh "
BBFILE_PATTERN_meta-asicsagh := "^${LAYERDIR}/"
BBFILES_PRIORITY_meta-asicsagh = "7"
LAYERSERIES_COMPAT_meta-asicsagh = "master walnascar"
BBDEBUG = "yes"
